# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flix' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flix

pod 'AlamofireImage'

  target 'FlixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlixUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
